env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-tabs: 0,
  indent: 0,
  no-console: 0,
  import/extensions: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
}
